---
- name: Update IPA/IdM cluster
  hosts: ipaserver,ipareplicas
  become: true
  serial: 1
  vars:
    always_reboot: false
    # Documented RHEL IdM recommendation is "at least 10 minutes"
    pause_between_servers_minutes: 10
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        update_cache: true
        state: latest
      register: package_install

    - name: Install python3-tracer package
      yum:
        name: python3-tracer
        state: present

    - name: Check need for rebooting
      command: tracer -a
      register: needs_rebooting
      failed_when: false
      changed_when: false

    - name: Reboot system
      reboot:
      register: system_rebooted
      when: always_reboot | bool or
            needs_rebooting.rc != 0

    - name: Pause before updating next server
      pause:
        minutes: "{{ pause_between_servers_minutes }}"
      when: package_install is changed or
            system_rebooted is changed
