---
- name: Setup IPA/IdM sudo rules
  hosts: ipaserver
  become: true
  vars_files:
    - vars_sudo.yml
    - vault_ipa.yml
  tasks:
    - name: Delete sudo rule
      ipasudorule:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_sudo_rules_delete | default([]) | select() | list }}"

    - name: Delete sudo command group
      ipasudocmdgroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_sudo_command_groups_delete | default([]) | select() | list }}"

    - name: Delete sudo command
      ipasudocmd:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_sudo_commands_delete | default([]) | select() | list }}"

    - name: Create sudo command
      ipasudocmd:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: present
      loop: "{{ ipa_sudo_commands_create | default([]) | select() | list }}"

    - name: Create sudo command group
      ipasudocmdgroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        sudocmd: "{{ item.commands | default(omit) }}"
        action: sudocmdgroup
        state: present
      loop: "{{ ipa_sudo_command_groups_create | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create sudo rule
      ipasudorule:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        user: "{{ item.users | default(omit) }}"
        group: "{{ item.groups | default(omit) }}"
        usercategory: "{{ 'all' if 'users' not in item and 'groups' not in item else '' }}"
        host: "{{ item.hosts | default(omit) }}"
        hostgroup: "{{ item.hostgroups | default(omit) }}"
        hostcategory: "{{ 'all' if 'hosts' not in item and 'hostgroups' not in item else '' }}"
        allow_sudocmd: "{{ item.commands | default(omit) }}"
        allow_sudocmdgroup: "{{ item.command_groups | default(omit) }}"
        cmdcategory: "{{ 'all' if 'commands' not in item and 'command_groups' not in item else '' }}"
        runasuser: "{{ item.runasusers | default(omit) }}"
        runasgroup: "{{ item.runagroups | default(omit) }}"
        #runasusercategory: "{{ 'all' if 'runasusers' not in item else omit }}"
        #runasgroupcategory: "{{ 'all' if 'runasgroups' not in item else omit }}"
        sudooption: "{{ item.sudo_options | default(omit) }}"
        order: "{{ item.order | default(omit) }}"
        action: sudorule
        state: present
      loop: "{{ ipa_sudo_rules_create | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"
