---
- name: Configure IPA/IdM
  hosts: ipaserver
  become: true
  vars_files:
    - vault_ipa.yml
  vars:
    # https://bugzilla.redhat.com/show_bug.cgi?id=2121099
    ipa_admin_password_expire: 2089-12-31 23:59:59
    # TODO: Configure CRL publisher server
    # https://github.com/freeipa/ansible-freeipa/issues/883
    ipa_ca_renewal_server: idm1.sub.example.com
    ipa_servers_visible:
      - idm1.sub.example.com
      - idm2.sub.example.com
    ipa_servers_hidden:
      - idm3.sub.example.com
    ipa_topology_segments_add:
      - { suffix: domain+ca, left: idm1.sub.example.com, right: idm2.sub.example.com }
      - { suffix: domain+ca, left: idm1.sub.example.com, right: idm3.sub.example.com }
      - { suffix: domain+ca, left: idm2.sub.example.com, right: idm3.sub.example.com }
    ipa_topology_segments_remove:
      - { suffix: domain+ca, left: idm1.sub.example.com, right: lost.sub.example.com }
  tasks:
    - name: Verify configuration
      assert:
        that:
          - ipa_ca_renewal_server not in ipa_servers_hidden | select() | list
        fail_msg: "CA renewal server cannot be hidden"
        success_msg: "Configuration verified"

    - name: Configure admin password expiration
      ipauser:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ ipaadmin_principal }}"
        passwordexpiration: "{{ ipa_admin_password_expire }}"
      when: ipa_admin_password_expire | default(false)

    - name: Configure servers visible
      ipaserver:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        hidden: false
      loop: "{{ ipa_servers_visible }}"

    - name: Configure CA renewal server
      ipaconfig:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        ca_renewal_master_server: "{{ ipa_ca_renewal_server }}"
      when: ipa_ca_renewal_server | default(false)

    - name: Configure servers hidden
      ipaserver:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        hidden: true
      loop: "{{ ipa_servers_hidden | select() | list }}"

    - name: Add topology segment
      ipatopologysegment:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        suffix: "{{ item.suffix }}"
        name: "{{ item.name | default(omit) }}"
        left: "{{ item.left }}"
        right: "{{ item.right }}"
        state: present
      loop: "{{ ipa_topology_segments_add | default([]) | select() | list }}"

    - name: Remove topology segment
      ipatopologysegment:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        suffix: "{{ item.suffix }}"
        name: "{{ item.name | default(omit) }}"
        left: "{{ item.left }}"
        right: "{{ item.right }}"
        state: absent
      loop: "{{ ipa_topology_segments_remove | default([]) | select() | list }}"

    - name: Verify topology suffix
      ipatopologysuffix:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        suffix: domain
        state: verified
      changed_when: false
      loop:
        - ca
        - domain
