---
- name: Setup IPA/IdM HBAC rules
  hosts: ipaserver
  become: true
  gather_facts: false
  vars_files:
    - vars_hbac.yml
    - vault_ipa.yml
  tasks:
    - name: Configure default allow_all HBAC rule
      ipahbacrule:
        name: allow_all
        state: "{{ ipa_hbac_allow_all }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      when: ipa_hbac_allow_all | default(false)

    - name: Delete HBAC rule
      # noqa: no-log-password
      ipahbacrule:
        name: "{{ item }}"
        state: absent
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_rules_delete | default([]) | select }}"

    - name: Delete HBAC service group
      # noqa: no-log-password
      ipahbacsvcgroup:
        name: "{{ item }}"
        state: absent
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_service_groups_delete | default([]) | select }}"

    - name: Delete HBAC service
      # noqa: no-log-password
      ipahbacsvc:
        name: "{{ item }}"
        state: absent
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_services_delete | default([]) | select }}"

    - name: Create HBAC service
      # noqa: no-log-password
      ipahbacsvc:
        name: "{{ item.name }}"
        state: present
        description: "{{ item.description | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_services_create | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create HBAC service group
      # noqa: no-log-password
      ipahbacsvcgroup:
        name: "{{ item.name }}"
        state: present
        action: hbacsvcgroup
        description: "{{ item.description | default(omit) }}"
        hbacsvc: "{{ item.services | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_service_groups_create | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create HBAC rule
      # noqa: no-log-password
      ipahbacrule:
        name: "{{ item.name }}"
        state: present
        action: hbacrule
        description: "{{ item.description | default(omit) }}"
        user: "{{ item.users | default(omit) }}"
        group: "{{ item.groups | default(omit) }}"
        usercategory: "{{ 'all' if 'users' not in item and 'groups' not in item else '' }}"
        host: "{{ item.hosts | default(omit) }}"
        hostgroup: "{{ item.hostgroups | default(omit) }}"
        hostcategory: "{{ 'all' if 'hosts' not in item and 'hostgroups' not in item else '' }}"
        hbacsvc: "{{ item.services | default(omit) }}"
        hbacsvcgroup: "{{ item.service_groups | default(omit) }}"
        servicecategory: "{{ 'all' if 'services' not in item and 'service_groups' not in item else '' }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hbac_rules_create | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"
