---
- name: Install IPA/IdM client
  hosts: ipaclients
  become: true
  gather_facts: false
  vars_files:
    - vars_dns.yml
    - vars_ipa.yml
    - vault_ipa.yml
  roles:
    - role: ipaclient
      state: present
