---
- name: Restore IPA/IdM server backup
  hosts: ipabackup
  become: true
  gather_facts: false
  vars_files:
    - vault_ipa.yml
  vars:
    ipabackup_from_controller: true
    ipabackup_controller_path: /var/backup
    ipabackup_name: "{{ ipaserver_backup_name }}"
    ipabackup_password: "{{ ipadm_password }}"

    ipabackup_setup_firewalld: "{{ ipacluster_setup_firewalld }}"
    ipabackup_firewalld_zone: "{{ ipacluster_firewalld_zone }}"
  roles:
    - role: ipabackup
      state: restored
