---
- name: Update IPA/IdM cluster
  hosts: ipaserver,ipareplicas
  become: true
  serial: 1
  vars:
    always_reboot: false
    # Documented RHEL IdM recommendation is "at least 10 minutes"
    pause_between_servers_minutes: 10
  tasks:
    - name: Update all packages
      # noqa: package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      register: package_install

    - name: Install dnf-plugins-core package
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Check need for rebooting
      check_mode: false
      ansible.builtin.command: dnf -C --disableplugin=product-id,subscription-manager needs-restarting
      register: needs_rebooting
      failed_when: false
      changed_when: false

    - name: Reboot system
      ansible.builtin.reboot:
      register: system_rebooted
      when: (always_reboot | bool) or
            (needs_rebooting.stdout_lines is defined and needs_rebooting.stdout_lines | length > 0)

    - name: Pause before updating next server
      ansible.builtin.pause:
        minutes: "{{ pause_between_servers_minutes }}"
      when: package_install is changed or
            system_rebooted is changed
