---
- name: Setup IPA/IdM users and groups
  hosts: ipaserver
  become: true
  vars_files:
    - vars_users.yml
    - vault_ipa.yml
  vars:
    # Operating one by one is much slower but
    # allows seeing affected users and groups
    # NB. Does not apply to all operations
    operate_one_by_one: false
  tasks:
    # Loop to display items
    - name: Delete groups
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ [ipa_groups_delete | default([])] | select() | list }}"
      when: not operate_one_by_one | bool

    - name: Delete group
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_groups_delete | default([]) | select() | list }}"
      when: operate_one_by_one | bool

    - name: Remove group members
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        user: "{{ item.users | default(omit) }}"
        group: "{{ item.groups | default(omit) }}"
        action: member
        state: absent
      loop: "{{ ipa_group_members_remove | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"

    # Loop to display items
    - name: Delete users
      ipauser:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ [ipa_users_delete | default([])] | select() | list }}"
      when: not operate_one_by_one | bool

    - name: Delete user
      ipauser:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_users_delete | default([]) | select() | list }}"
      when: operate_one_by_one | bool

    # Loop to display items
    - name: Create groups
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: present
      loop: "{{ [ipa_groups_create | default([])] | select() | list }}"
      loop_control:
        label: "{{ item | map(attribute='name') }}"
      # https://github.com/freeipa/ansible-freeipa/issues/879
      when: false and not operate_one_by_one | bool

    - name: Create group
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        gidnumber: "{{ item.gid | default(omit) }}"
        state: present
      loop: "{{ ipa_groups_create | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"
      # https://github.com/freeipa/ansible-freeipa/issues/879
      when: true or operate_one_by_one | bool

    # Loop to display items
    - name: Create users
      ipauser:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        users: "{{ item }}"
        update_password: on_create
        state: present
      loop: "{{ [ipa_users_create | default([])] | select() | list }}"
      loop_control:
        label: "{{ item | map(attribute='name') }}"
      when: not operate_one_by_one | bool

    - name: Create user
      ipauser:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        password: "{{ item.password | default(omit) }}"
        first: "{{ item.first | default(omit) }}"
        last: "{{ item.last | default(omit) }}"
        email: "{{ item.email | default(omit) }}"
        uid: "{{ item.uid | default(omit) }}"
        gid: "{{ item.gid | default(omit) }}"
        noprivate: "{{ item.noprivate | default(omit) }}"
        homedir: "{{ item.homedir | default(omit) }}"
        shell: "{{ item.shell | default(omit) }}"
        principalexpiration: "{{ item.principalexpiration | default(omit) }}"
        passwordexpiration: "{{ item.passwordexpiration | default(omit) }}"
        update_password: on_create
        state: present
      loop: "{{ ipa_users_create | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: operate_one_by_one | bool

    - name: Add group members
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        user: "{{ item.users | default(omit) }}"
        group: "{{ item.groups | default(omit) }}"
        action: member
        state: present
      loop: "{{ ipa_group_members_add | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Explicitly set group members
      ipagroup:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        user: "{{ item.users | default(omit) }}"
        group: "{{ item.groups | default(omit) }}"
        action: group
        state: present
      loop: "{{ ipa_group_members_set | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete user self service rule
      ipaselfservice:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ ipa_selfservice_delete | default([]) | select() | list }}"

    - name: Create user self service rules
      ipaselfservice:
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
        name: "{{ item.name }}"
        attribute: "{{ item.attributes }}"
        permission: "{{ item.permissions }}"
        state: present
      loop: "{{ ipa_selfservice_create | default([]) | select() | list }}"
      loop_control:
        label: "{{ item.name }}"
