---
- name: Restore IPA/IdM server backup
  hosts: ipaserver
  become: true
  vars_files:
    - vault_ipa.yml
  vars:
    ipabackup_from_controller: true
    ipabackup_controller_path: /var/backup
    ipabackup_name: "{{ ipaserver_backup_name }}"
    ipabackup_password: "{{ ipadm_password }}"

    #ipabackup_setup_firewalld: true
    #ipabackup_firewalld_zone: public
  roles:
  - role: ipabackup
    state: restored
