---
- name: Restore IPA/IdM server backup
  hosts: ipaserver
  become: true
  vars_files:
    - vault_ipa.yml
  vars:
    ipabackup_from_controller: true
    ipabackup_controller_path: /var/backup
    ipabackup_name: idm1.sub.example.com_ipa-full-2022-08-09-12-11-40
    ipabackup_password: "{{ ipaserver_dirsrv_pin }}"

    #ipabackup_setup_firewalld: true
    #ipabackup_firewalld_zone: public
  roles:
  - role: ipabackup
    state: restored
