---
- name: Install IPA/IdM server
  hosts: ipaserver
  become: true
  gather_facts: false
  vars_files:
    - vars_ad.yml
    - vars_ca.yml
    - vars_dns.yml
    - vars_ipa.yml
    - vault_ipa.yml
  roles:
    - role: ipaserver
      state: present
