---
- name: Install IPA/IdM replica
  hosts: ipareplicas
  become: true
  vars_files:
    - vars_ad.yml
    - vars_ca.yml
    - vars_dns.yml
    - vars_ipa.yml
    - vault_ipa.yml
  roles:
    - role: ipareplica
      state: present
