---
- name: Setup IPA/IdM hosts and hostgroups
  hosts: ipaserver
  become: true
  gather_facts: false
  vars_files:
    - vars_dns.yml
    - vars_hosts.yml
    - vault_ipa.yml
  tasks:
    - name: Delete host group
      # noqa: no-log-password
      ipahostgroup:
        name: "{{ item }}"
        state: absent
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hostgroups_delete | default([]) | select }}"

    - name: Remove host group members
      # noqa: no-log-password
      ipahostgroup:
        name: "{{ item.name }}"
        state: absent
        action: member
        host: "{{ item.hosts | default(omit) }}"
        hostgroup: "{{ item.hostgroups | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hostgroup_members_remove | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Delete host
      # noqa: no-log-password
      ipahost:
        name: "{{ item }}"
        state: absent
        update_dns: "{{ ipaserver_setup_dns | default(false) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hosts_delete | default([]) | select }}"

    - name: Disable host
      # noqa: no-log-password
      ipahost:
        name: "{{ item }}"
        state: disabled
        update_dns: "{{ ipaserver_setup_dns | default(false) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hosts_disable | default([]) | select }}"

    - name: Create host group
      # noqa: no-log-password
      ipahostgroup:
        name: "{{ item.name }}"
        state: present
        description: "{{ item.description | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hostgroups_create | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create host
      # noqa: no-log-password
      ipahost:
        name: "{{ item }}"
        state: present
        force: true
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hosts_create | default([]) | select }}"
      loop_control:
        label: "{{ item }}"

    - name: Add host group members
      # noqa: no-log-password
      ipahostgroup:
        name: "{{ item.name }}"
        action: member
        host: "{{ item.hosts | default(omit) }}"
        hostgroup: "{{ item.hostgroups | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hostgroup_members_add | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Explicitly set host group members
      # noqa: no-log-password
      ipahostgroup:
        name: "{{ item.name }}"
        action: hostgroup
        host: "{{ item.hosts | default(omit) }}"
        hostgroup: "{{ item.hostgroups | default(omit) }}"
        ipaadmin_principal: "{{ ipaadmin_principal }}"
        ipaadmin_password: "{{ ipaadmin_password }}"
      loop: "{{ ipa_hostgroup_members_set | default([]) | select }}"
      loop_control:
        label: "{{ item.name }}"
