---
- name: Update IPA/IdM servers
  hosts: ipaserver,ipareplicas
  become: true
  serial: 1
  vars:
    # Documented RHEL IdM recommendation is "at least 10 minutes"
    pause_between_servers_mins: 10
  tasks:
    - name: Install yum-utils package
      yum:
        name: yum-utils
        state: present

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Check need for rebooting
      command: needs-restarting -r
      register: needs_restarting
      failed_when: false
      changed_when: false
                    
    - name: Reboot system
      reboot:
      when: needs_restarting.rc != 0

    - name: Pause before updating next server
      pause:
        minutes: "{{ pause_between_servers_mins }}"
